[[language]]
name = "c"
auto-format = false
indent = {tab-width = 4, unit = "    "}
file-types = ["c", "h"]

[[language]]
name = "rust"
auto-format = false
language-server = {command = "rust-analyzer"}
indent = {tab-width = 4, unit = "    "}
roots = ["Cargo.lock", "Cargo.toml"]
[language.config]
checkOnSave = {enable=true, command="clippy"}
# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"
# [language.debugger.templates]
# name = "binary"
# request = "launch"
# [language.debugger.templates.completion]
# completion = "filename"
# name = "binary"
# [language.debugger.templates.args]
# program = "{0}"
# runInTerminal = true

[[language]]
name = "python"
auto-format = false
formatter = {command = "black", args = ["--quiet", "-"]}
indent = {tab-width = 4, unit = "    "}
shebangs = ["python"]

[[language]]
name = "bash"
auto-format = false
formatter = {command = 'shfmt', args = ["-i", "4"]}
indent = {tab-width = 4, unit = "    "}
shebangs = ["sh", "bash", "zsh", "dash"]

[[language]]
name = "markdown"
auto-format = false
language-server = {command = "ltex-ls"}
indent = {tab-width = 4, unit = "    "}
file-types = ["md", "txt"]
[[language.config]]
ltex.language = "en-US"
ltex.dictionary = ":~/.config/helix/ltex.dictionary.en-US.txt"
# ltex-ls binary: https://github.com/valentjn/ltex-ls/releases
# mv extracted foler to /opt named as ltex-ls
# PATH="/opt/ltex-ls/bin:$PATH"

[[language]]
name = "git-commit"
auto-format = false
language-server = {command = "ltex-ls"}
indent = {tab-width = 4, unit = "    "}
rulers = [80]
[[language.config]]
ltex.language = "en-US"
ltex.dictionary = ":~/.config/helix/ltex.dictionary.en-US.txt"
# ltex-ls binary: https://github.com/valentjn/ltex-ls/releases
# mv extracted foler to /opt named as ltex-ls
# PATH="/opt/ltex-ls/bin:$PATH"

[[language]]
name = "latex"
language-server = {command = "ltex-ls"}
indent = {tab-width = 4, unit = "    "}
file-types = ["tex"]
[[language.config]]
ltex.language = "en-US"
ltex.dictionary = ":~/.config/helix/ltex.dictionary.en-US.txt"
# ltex-ls binary: https://github.com/valentjn/ltex-ls/releases
# mv extracted foler to /opt named as ltex-ls
# PATH="/opt/ltex-ls/bin:$PATH"

[[language]]
name = "typescript"
auto-format = false
indent = {tab-width = 4, unit = "    "}
language-server = {command = "typescript-language-server", args = ["--stdio"]}

[[language]]
name = "toml"
auto-format = false
indent = {tab-width = 4, unit = "    "}

[[language]]
name = "yaml"
auto-format = false
indent = {tab-width = 2, unit = "  "}
[language.config]
yaml = {keyOrdering = false}

[[language]]
name = "css"
auto-format = false
indent = {tab-width = 2, unit = "  "}

[[language]]
name = "html"
auto-format = false
indent = {tab-width = 2, unit = "  "}

